name: rive_viewmodel_generator
description: A tool to parse Rive files and generate view model definitions
version: 1.0.0

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: '>=3.32.0'

dependencies:
  collection: ^1.18.0
  dart_style: ^3.1.0
  flutter:
    sdk: flutter
  rive: ^0.14.1
  desktop_drop: ^0.6.0
  code_builder: ^4.10.1
  file_picker: ^10.1.9
  universal_html: ^2.2.4
  mustache_template: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^6.0.0
  lints: ^6.0.0 

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: false
    rive: false
    lottie: false

flutter:
  uses-material-design: true
  
  assets:
    - assets/templates/dart/